// Mock dependencies before imports
jest.mock('@/lib/utils/logger');
jest.mock('ai', () => ({
  generateText: jest.fn(),
}));
jest.mock('@ai-sdk/openai', () => ({
  openai: jest.fn(() => 'mock-model'),
}));
jest.mock('@/lib/mastra/tools/chart-data-analysis.tool', () => ({
  chartDataAnalysisTool: {
    execute: jest.fn(),
  },
}));

import { enhancedChartControlTool } from '@/lib/mastra/tools/enhanced-chart-control.tool';
import { logger } from '@/lib/utils/logger';
import { generateText } from 'ai';
import { chartDataAnalysisTool } from '@/lib/mastra/tools/chart-data-analysis.tool';
import type {
  MockEnhancedChartControlExecute,
  createMockTextResponse
} from './enhanced-chart-control.tool.test.types';

// Type the execute function properly
const executeEnhancedChartControl = enhancedChartControlTool.execute as MockEnhancedChartControlExecute;

// Mock generateText
const mockGenerateText = generateText as jest.MockedFunction<typeof generateText>;

// Mock chart analysis data
const mockChartAnalysis = {
  rawData: {
    candles: [
      { time: 1000, open: 100, high: 110, low: 90, close: 105, volume: 1000 },
      { time: 2000, open: 105, high: 115, low: 95, close: 110, volume: 1200 },
    ],
  },
  candles: [
    { time: 1000, open: 100, high: 110, low: 90, close: 105, volume: 1000 },
    { time: 2000, open: 105, high: 115, low: 95, close: 110, volume: 1200 },
  ],
  trend: {
    direction: 'bullish' as const,
  },
  recommendations: {
    trendlineDrawing: [
      {
        points: [
          { time: 1000, price: 95 },
          { time: 2000, price: 100 },
        ],
        style: { color: '#00E676', lineWidth: 2, lineStyle: 'solid' },
        description: 'Primary uptrend line',
        confidence: 0.9,
      },
      {
        points: [
          { time: 1000, price: 110 },
          { time: 2000, price: 115 },
        ],
        style: { color: '#2196F3', lineWidth: 2, lineStyle: 'solid' },
        description: 'Resistance line',
        confidence: 0.8,
      },
    ],
  },
};

describe('enhancedChartControlTool', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  describe('tool configuration', () => {
    it('should have correct metadata', () => {
      expect(enhancedChartControlTool.id).toBe('enhanced-chart-control');
      expect(enhancedChartControlTool.description).toContain('Enhanced AI-powered chart control');
      expect(enhancedChartControlTool.description).toContain('Multiple drawings');
      expect(enhancedChartControlTool.description).toContain('Batch operations');
      expect(enhancedChartControlTool.inputSchema).toBeDefined();
      expect(enhancedChartControlTool.outputSchema).toBeDefined();
    });
  });

  describe('execute - successful operations', () => {

    beforeEach(() => {
      (chartDataAnalysisTool.execute as jest.Mock).mockResolvedValue(mockChartAnalysis);
    });

    it('should handle single trendline drawing request', async () => {
      mockGenerateText
        .mockResolvedValueOnce({
          text: JSON.stringify({
            operations: [{
              type: 'drawing_operation',
              action: 'draw_trendline',
              parameters: {},
              priority: 5,
              description: 'Draw single trendline',
            }],
            reasoning: 'User wants a single trendline',
            confidence: 0.9,
            complexity: 'simple',
            userIntent: 'Draw trendline',
            requiresMultiple: false,
          }),
        } as any)
        .mockResolvedValueOnce({
          text: '�������;W~W_',
        } as any);

      const result = await executeEnhancedChartControl({
        context: {
          userRequest: '������Df',
          currentState: {
            symbol: 'BTCUSDT',
            timeframe: '1h',
          },
        },
      });

      expect(result.success).toBe(true);
      expect(result.operations).toHaveLength(1);
      expect(result.operations[0]).toMatchObject({
        type: 'drawing_operation',
        action: 'draw_trendline',
        parameters: {
          points: mockChartAnalysis.recommendations.trendlineDrawing[0].points,
          style: mockChartAnalysis.recommendations.trendlineDrawing[0].style,
          autoGenerated: true,
        },
        clientEvent: {
          event: 'draw:trendline',
          data: {
            points: mockChartAnalysis.recommendations.trendlineDrawing[0].points,
            style: mockChartAnalysis.recommendations.trendlineDrawing[0].style,
          },
        },
      });
      expect(result.metadata.chartDataUsed).toBe(true);
    });

    it('should handle multiple trendline drawing request', async () => {
      mockGenerateText
        .mockResolvedValueOnce({
          text: JSON.stringify({
            operations: [{
              type: 'drawing_operation',
              action: 'draw_trendline',
              parameters: {},
              priority: 5,
              description: 'Draw multiple trendlines',
              repeatCount: 3,
            }],
            reasoning: 'User wants 3 trendlines',
            confidence: 0.9,
            complexity: 'moderate',
            userIntent: 'Draw 3 trendlines',
            requiresMultiple: true,
          }),
        } as any)
        .mockResolvedValueOnce({
          text: '3,n�������;W~W_',
        } as any);

      const result = await executeEnhancedChartControl({
        context: {
          userRequest: '3,n������Df',
          currentState: {
            symbol: 'BTCUSDT',
            timeframe: '1h',
          },
        },
      });

      expect(result.success).toBe(true);
      expect(result.operations).toHaveLength(3);
      expect(result.metadata.multipleOperations).toBe(true);
      
      // Check first two use recommendations
      expect(result.operations[0].parameters).toMatchObject({
        points: mockChartAnalysis.recommendations.trendlineDrawing[0].points,
        autoGenerated: true,
      });
      expect(result.operations[1].parameters).toMatchObject({
        points: mockChartAnalysis.recommendations.trendlineDrawing[1].points,
        autoGenerated: true,
      });
      
      // Third should be synthetic
      expect(result.operations[2].parameters).toMatchObject({
        autoGenerated: true,
        synthetic: true,
      });
    });

    it('should handle Japanese number expressions', async () => {
      const testCases = [
        { request: '�,n������Df', expectedCount: 5 },
        { request: 'pn������Df', expectedCount: 3 }, // Default for p
        { request: '_OU�������Df', expectedCount: 5 }, // Default for _OU�
      ];

      for (const testCase of testCases) {
        mockGenerateText
          .mockResolvedValueOnce({
            text: JSON.stringify({
              operations: [{
                type: 'drawing_operation',
                action: 'draw_trendline',
                parameters: {},
                priority: 5,
                repeatCount: testCase.expectedCount,
              }],
              reasoning: 'Multiple lines requested',
              confidence: 0.9,
              complexity: 'moderate',
              userIntent: 'Draw multiple lines',
              requiresMultiple: true,
            }),
          } as any)
          .mockResolvedValueOnce({
            text: `${testCase.expectedCount},n�������;W~W_`,
          } as any);

        const result = await executeEnhancedChartControl({
          context: {
            userRequest: testCase.request,
            currentState: {},
          },
        });

        expect(result.operations).toHaveLength(testCase.expectedCount);
      }
    });

    it('should handle symbol change operation', async () => {
      mockGenerateText
        .mockResolvedValueOnce({
          text: JSON.stringify({
            operations: [{
              type: 'symbol_change',
              action: 'change_symbol',
              parameters: { symbol: 'ETHUSDT' },
              priority: 5,
              description: 'Change to ETH',
            }],
            reasoning: 'User wants to change symbol',
            confidence: 0.95,
            complexity: 'simple',
            userIntent: 'Change symbol',
            requiresMultiple: false,
          }),
        } as any)
        .mockResolvedValueOnce({
          text: 'ETHUSDTk��H~W_',
        } as any);

      const result = await executeEnhancedChartControl({
        context: {
          userRequest: 'ETHk��Hf',
          currentState: { symbol: 'BTCUSDT' },
        },
      });

      expect(result.success).toBe(true);
      expect(result.operations[0]).toMatchObject({
        type: 'symbol_change',
        action: 'change_symbol',
        parameters: { symbol: 'ETHUSDT' },
        clientEvent: {
          event: 'ui:changeSymbol',
          data: { symbol: 'ETHUSDT' },
        },
      });
    });

    it('should handle timeframe change operation', async () => {
      mockGenerateText
        .mockResolvedValueOnce({
          text: JSON.stringify({
            operations: [{
              type: 'timeframe_change',
              action: 'change_timeframe',
              parameters: { timeframe: '4h' },
              priority: 5,
              description: 'Change to 4h',
            }],
            reasoning: 'User wants to change timeframe',
            confidence: 0.95,
            complexity: 'simple',
            userIntent: 'Change timeframe',
            requiresMultiple: false,
          }),
        } as any)
        .mockResolvedValueOnce({
          text: '4B��k��H~W_',
        } as any);

      const result = await executeEnhancedChartControl({
        context: {
          userRequest: '4B��kWf',
          currentState: { timeframe: '1h' },
        },
      });

      expect(result.success).toBe(true);
      expect(result.operations[0]).toMatchObject({
        type: 'timeframe_change',
        action: 'change_timeframe',
        parameters: { timeframe: '4h' },
        clientEvent: {
          event: 'ui:changeTimeframe',
          data: { timeframe: '4h' },
        },
      });
    });

    it('should handle batch operations', async () => {
      mockGenerateText
        .mockResolvedValueOnce({
          text: JSON.stringify({
            operations: [{
              type: 'batch_operation',
              action: 'clear_all_drawings',
              parameters: { clearAll: true },
              priority: 5,
              description: 'Clear all drawings',
            }],
            reasoning: 'User wants to clear all drawings',
            confidence: 0.9,
            complexity: 'simple',
            userIntent: 'Clear all',
            requiresMultiple: false,
          }),
        } as any)
        .mockResolvedValueOnce({
          text: 'Yyfn�;�JdW~W_',
        } as any);

      const result = await executeEnhancedChartControl({
        context: {
          userRequest: 'Yyfn�;�Jd',
          currentState: {
            existingDrawings: [
              { id: 'draw-1', type: 'trendline' },
              { id: 'draw-2', type: 'trendline' },
            ],
          },
        },
      });

      expect(result.success).toBe(true);
      expect(result.operations[0]).toMatchObject({
        type: 'batch_operation',
        action: 'clear_all_drawings',
        clientEvent: {
          event: 'chart:batchOperation',
          data: { clearAll: true },
        },
      });
    });
  });

  describe('execute - error handling', () => {
    it('should handle chart analysis failure gracefully', async () => {
      (chartDataAnalysisTool.execute as jest.Mock).mockRejectedValue(new Error('API error'));

      mockGenerateText
        .mockResolvedValueOnce({
          text: JSON.stringify({
            operations: [{
              type: 'drawing_operation',
              action: 'draw_trendline',
              parameters: {},
              priority: 5,
            }],
            reasoning: 'Drawing without analysis',
            confidence: 0.5,
            complexity: 'simple',
            userIntent: 'Draw line',
            requiresMultiple: false,
          }),
        } as any)
        .mockResolvedValueOnce({
          text: '�������;W~W_',
        } as any);

      const result = await executeEnhancedChartControl({
        context: {
          userRequest: '������Df',
          currentState: {},
        },
      });

      expect(logger.warn).toHaveBeenCalledWith(
        '[EnhancedChartControl] Chart analysis failed',
        expect.any(Object)
      );
      expect(result.success).toBe(true);
      expect(result.metadata.chartDataUsed).toBe(false);
    });

    it('should handle AI parsing error with fallback', async () => {
      (chartDataAnalysisTool.execute as jest.Mock).mockResolvedValue(mockChartAnalysis);

      mockGenerateText
        .mockResolvedValueOnce({
          text: 'Invalid JSON response',
        } as any)
        .mockResolvedValueOnce({
          text: 'թ���ïg�������;W~W_',
        } as any);

      const result = await executeEnhancedChartControl({
        context: {
          userRequest: '������Df',
          currentState: {},
        },
      });

      expect(logger.error).toHaveBeenCalledWith(
        '[EnhancedChartControl] Parse error',
        expect.any(Object)
      );
      expect(result.success).toBe(true);
      expect(result.operations).toHaveLength(1);
      expect(result.operations[0].parameters).toMatchObject({
        points: mockChartAnalysis.recommendations.trendlineDrawing[0].points,
        autoGenerated: true,
      });
    });

    it('should handle complete execution failure', async () => {
      mockGenerateText.mockRejectedValue(new Error('OpenAI API error'));

      const result = await executeEnhancedChartControl({
        context: {
          userRequest: '������Df',
          currentState: {},
        },
      });

      expect(result.success).toBe(false);
      expect(result.error).toBe('OpenAI API error');
      expect(result.response).toBe('申し訳ございません。リクエストの処理中にエラーが発生しました。');
      expect(result.metadata.confidence).toBe(0);
    });

    it('should handle markdown-wrapped JSON response', async () => {
      const validJson = {
        operations: [{
          type: 'drawing_operation',
          action: 'draw_trendline',
          parameters: {},
          priority: 5,
        }],
        reasoning: 'Test',
        confidence: 0.9,
        complexity: 'simple',
        userIntent: 'Test',
        requiresMultiple: false,
      };

      const wrappedResponses = [
        `\`\`\`json\n${JSON.stringify(validJson)}\n\`\`\``,
        `\`\`\`${JSON.stringify(validJson)}\`\`\``,
        `\`\`\`\n${JSON.stringify(validJson)}\n\`\`\``,
      ];

      for (const wrapped of wrappedResponses) {
        mockGenerateText
          .mockResolvedValueOnce({ text: wrapped } as any)
          .mockResolvedValueOnce({ text: 'Success' } as any);

        const result = await executeEnhancedChartControl({
          context: {
            userRequest: 'Test',
            currentState: {},
          },
        });

        expect(result.success).toBe(true);
        expect(result.operations).toHaveLength(1);
      }
    });
  });

  describe('synthetic drawing generation', () => {
    it('should generate synthetic drawings when no recommendations available', async () => {
      (chartDataAnalysisTool.execute as jest.Mock).mockResolvedValue({
        candles: [
          { time: 1000, open: 100, high: 110, low: 90, close: 105, volume: 1000 },
          { time: 2000, open: 105, high: 115, low: 95, close: 110, volume: 1200 },
        ],
        trend: { direction: 'neutral' },
        recommendations: { trendlineDrawing: [] },
      });

      mockGenerateText
        .mockResolvedValueOnce({
          text: JSON.stringify({
            operations: [{
              type: 'drawing_operation',
              action: 'draw_trendline',
              parameters: {},
              priority: 5,
              repeatCount: 3,
            }],
            reasoning: 'Multiple lines without recommendations',
            confidence: 0.7,
            complexity: 'moderate',
            userIntent: 'Draw lines',
            requiresMultiple: true,
          }),
        } as any)
        .mockResolvedValueOnce({
          text: '3,n�������;W~W_',
        } as any);

      const result = await executeEnhancedChartControl({
        context: {
          userRequest: '3,n������Df',
          currentState: {},
        },
      });

      expect(result.success).toBe(true);
      expect(result.operations).toHaveLength(3);
      
      // All should be synthetic
      result.operations.forEach((op, idx) => {
        expect(op.parameters).toMatchObject({
          autoGenerated: true,
          synthetic: true,
          index: idx,
          total: 3,
        });
        expect(op.parameters.points).toHaveLength(2);
      });
    });

    it('should generate trend-aware synthetic lines', async () => {
      const trendDirections = ['bullish', 'bearish', 'neutral'];
      
      for (const direction of trendDirections) {
        (chartDataAnalysisTool.execute as jest.Mock).mockResolvedValue({
          candles: [
            { time: 1000, open: 100, high: 110, low: 90, close: 105, volume: 1000 },
            { time: 2000, open: 105, high: 115, low: 95, close: 110, volume: 1200 },
          ],
          trend: { direction },
          recommendations: { trendlineDrawing: [] },
        });

        mockGenerateText
          .mockResolvedValueOnce({
            text: JSON.stringify({
              operations: [{
                type: 'drawing_operation',
                action: 'draw_trendline',
                parameters: {},
                priority: 5,
                repeatCount: 2,
              }],
              reasoning: 'Test trend direction',
              confidence: 0.7,
              complexity: 'moderate',
              userIntent: 'Draw lines',
              requiresMultiple: true,
            }),
          } as any)
          .mockResolvedValueOnce({
            text: '�������;W~W_',
          } as any);

        const result = await executeEnhancedChartControl({
          context: {
            userRequest: '2,n������Df',
            currentState: {},
          },
        });

        expect(result.success).toBe(true);
        expect(result.operations).toHaveLength(2);

        // Check slope direction based on trend
        result.operations.forEach(op => {
          const points = op.parameters.points as any[];
          const slope = points[1].price - points[0].price;
          
          if (direction === 'bullish') {
            expect(slope).toBeGreaterThan(0);
          } else if (direction === 'bearish') {
            expect(slope).toBeLessThan(0);
          }
          // neutral can be either positive or negative
        });
      }
    });
  });

  describe('color generation', () => {
    it('should assign distinct colors to multiple lines', async () => {
      (chartDataAnalysisTool.execute as jest.Mock).mockResolvedValue({
        candles: [],
        recommendations: { trendlineDrawing: [] },
      });

      mockGenerateText
        .mockResolvedValueOnce({
          text: JSON.stringify({
            operations: [{
              type: 'drawing_operation',
              action: 'draw_trendline',
              parameters: {},
              priority: 5,
              repeatCount: 8,
            }],
            reasoning: 'Many lines',
            confidence: 0.7,
            complexity: 'complex',
            userIntent: 'Draw many lines',
            requiresMultiple: true,
          }),
        } as any)
        .mockResolvedValueOnce({
          text: '8,n�������;W~W_',
        } as any);

      const result = await executeEnhancedChartControl({
        context: {
          userRequest: '8,n������Df',
          currentState: {},
        },
      });

      const colors = result.operations.map(op => op.parameters.style?.color);
      const uniqueColors = new Set(colors);
      
      // Should have 8 distinct colors
      expect(uniqueColors.size).toBe(8);
    });
  });

  describe('edge cases', () => {
    it('should handle empty user request', async () => {
      mockGenerateText
        .mockResolvedValueOnce({
          text: JSON.stringify({
            operations: [],
            reasoning: 'No clear intent',
            confidence: 0.1,
            complexity: 'simple',
            userIntent: 'Unknown',
            requiresMultiple: false,
          }),
        } as any)
        .mockResolvedValueOnce({
          text: 'Sample response text',
        } as any);

      const result = await executeEnhancedChartControl({
        context: {
          userRequest: '',
          currentState: {},
        },
      });

      expect(result.success).toBe(true);
      expect(result.operations).toHaveLength(0);
      expect(result.metadata.confidence).toBe(0.1);
    });

    it('should handle very large number requests with limit', async () => {
      mockGenerateText
        .mockResolvedValueOnce({
          text: JSON.stringify({
            operations: [{
              type: 'drawing_operation',
              action: 'draw_trendline',
              parameters: {},
              priority: 5,
              repeatCount: 100,
            }],
            reasoning: 'User wants many lines',
            confidence: 0.8,
            complexity: 'complex',
            userIntent: 'Draw many lines',
            requiresMultiple: true,
          }),
        } as any)
        .mockResolvedValueOnce({
          text: '_OU�n�������;W~W_',
        } as any);

      const result = await executeEnhancedChartControl({
        context: {
          userRequest: '100,n������Df',
          currentState: {},
        },
      });

      expect(result.success).toBe(true);
      // Should still generate 100 operations
      expect(result.operations).toHaveLength(100);
    });

    it('should handle mixed operations request', async () => {
      mockGenerateText
        .mockResolvedValueOnce({
          text: JSON.stringify({
            operations: [
              {
                type: 'symbol_change',
                action: 'change_symbol',
                parameters: { symbol: 'ETHUSDT' },
                priority: 1,
              },
              {
                type: 'timeframe_change',
                action: 'change_timeframe',
                parameters: { timeframe: '4h' },
                priority: 2,
              },
              {
                type: 'drawing_operation',
                action: 'draw_trendline',
                parameters: {},
                priority: 3,
                repeatCount: 2,
              },
            ],
            reasoning: 'Multiple different operations',
            confidence: 0.85,
            complexity: 'complex',
            userIntent: 'Complex setup',
            requiresMultiple: true,
          }),
        } as any)
        .mockResolvedValueOnce({
          text: 'ETHn4B��k��Hf2,n�������;W~W_',
        } as any);

      const result = await executeEnhancedChartControl({
        context: {
          userRequest: 'ETHn4B��g2,n������Df',
          currentState: {},
        },
      });

      expect(result.success).toBe(true);
      expect(result.operations).toHaveLength(4); // 2 changes + 2 drawings
      expect(result.operations[0].type).toBe('symbol_change');
      expect(result.operations[1].type).toBe('timeframe_change');
      expect(result.operations[2].type).toBe('drawing_operation');
      expect(result.operations[3].type).toBe('drawing_operation');
    });

    it('should handle concurrent executions', async () => {
      mockGenerateText.mockImplementation(() => 
        Promise.resolve({
          text: JSON.stringify({
            operations: [{
              type: 'drawing_operation',
              action: 'draw_trendline',
              parameters: {},
              priority: 5,
            }],
            reasoning: 'Test',
            confidence: 0.9,
            complexity: 'simple',
            userIntent: 'Test',
            requiresMultiple: false,
          }),
        } as any)
      );

      const promises = Array(5).fill(null).map((_, i) => 
        executeEnhancedChartControl({
          context: {
            userRequest: `Request ${i}`,
            currentState: {},
          },
        })
      );

      const results = await Promise.all(promises);
      expect(results).toHaveLength(5);
      results.forEach(result => {
        expect(result.success).toBe(true);
      });
    });

    it('should preserve existing drawings in state', async () => {
      const existingDrawings = [
        { id: 'existing-1', type: 'trendline' },
        { id: 'existing-2', type: 'support' },
      ];

      mockGenerateText
        .mockResolvedValueOnce({
          text: JSON.stringify({
            operations: [{
              type: 'drawing_operation',
              action: 'draw_trendline',
              parameters: {},
              priority: 5,
            }],
            reasoning: 'Add to existing',
            confidence: 0.9,
            complexity: 'simple',
            userIntent: 'Add line',
            requiresMultiple: false,
          }),
        } as any)
        .mockResolvedValueOnce({
          text: '�Xn�;k��W~W_',
        } as any);

      const result = await executeEnhancedChartControl({
        context: {
          userRequest: '�F1,��',
          currentState: {
            existingDrawings,
          },
        },
      });

      expect(result.success).toBe(true);
      expect(logger.info).toHaveBeenCalledWith(
        '[EnhancedChartControl] Processing request',
        expect.objectContaining({
          currentState: expect.objectContaining({
            existingDrawings,
          }),
        })
      );
    });
  });
});