name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Quick validation job
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Validate environment
      run: npm run env:check
      env:
        NEXT_PUBLIC_SUPABASE_URL: https://example.supabase.co
        NEXT_PUBLIC_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.example
        SUPABASE_SERVICE_ROLE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.service-example
        NEXT_PUBLIC_HUB_WS_URL: wss://hub.example.com/ws
        HUB_JWT_SECRET: this-is-a-32-character-secret-key
        BINANCE_WS_BASE_URL: wss://stream.binance.com:9443/ws
        REDIS_URL: redis://localhost:6379
        KAFKA_BROKER_URL: localhost:9092
        OPENAI_API_KEY: sk-test-key-for-ci
        
    - name: Type check
      run: npm run typecheck
      
    - name: Lint
      run: npm run lint
      
  # Call the comprehensive test workflow
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
    
  # Quick build check
  build:
    needs: validate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      env:
        NEXT_PUBLIC_SUPABASE_URL: https://example.supabase.co
        NEXT_PUBLIC_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.example
        SUPABASE_SERVICE_ROLE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.service-example
        NEXT_PUBLIC_HUB_WS_URL: wss://hub.example.com/ws
        HUB_JWT_SECRET: this-is-a-32-character-secret-key
        BINANCE_WS_BASE_URL: wss://stream.binance.com:9443/ws
        REDIS_URL: redis://localhost:6379
        KAFKA_BROKER_URL: localhost:9092
        OPENAI_API_KEY: sk-test-key-for-ci
        NEXT_TELEMETRY_DISABLED: 1